name: build
on:
  push:
    branches:
    - main
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --configuration Release test/LightningDbCache.Tests/LightningDbCache.Tests.csproj
        /p:CollectCoverage=true
        /p:CoverletOutput=TestResults/
        /p:coverletOutputFormat=lcov
    - name: Publish coverage report to coveralls.io   
      uses: coverallsapp/github-action@master   
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} 
        path-to-lcov: test/LightningDbCache.Tests/TestResults/coverage.info 